<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSvm42rx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSvm42rx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSvm42rx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSvm42rx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSvm42rx\appProdProjectContainer([
    'container.build_hash' => 'Svm42rx',
    'container.build_id' => '9c426928',
    'container.build_time' => 1669988497,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSvm42rx');
