<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMbcvpjz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMbcvpjz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMbcvpjz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMbcvpjz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMbcvpjz\appProdProjectContainer([
    'container.build_hash' => 'Mbcvpjz',
    'container.build_id' => 'a41010bc',
    'container.build_time' => 1669924315,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMbcvpjz');
