<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2dldjeq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2dldjeq/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2dldjeq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2dldjeq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2dldjeq\appProdProjectContainer([
    'container.build_hash' => '2dldjeq',
    'container.build_id' => '0c086861',
    'container.build_time' => 1669471562,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2dldjeq');
